# Generated by Django 5.0.3 on 2024-03-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_rename_cat_image_category_category_image'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Product',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('product_name', models.CharField(max_length=255)),
        #         ('product_price', models.PositiveIntegerField(blank=True)),
        #         ('product_image', models.ImageField(blank=True, upload_to='photos/products/<django.db.models.fields.related.ForeignKey>/main')),
        #         ('description', models.TextField(max_length=700)),
        #         ('is_active', models.BooleanField(default=False)),
        #         ('limited', models.IntegerField(default=-1)),
        #         ('slug', models.CharField(blank=True, max_length=200)),
        #         ('created_date', models.DateTimeField(auto_now_add=True)),
        #         ('modified_date', models.DateTimeField(auto_now=True)),
        #         ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Product_Supply',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('ps_stock', models.PositiveIntegerField(default=0)),
        #         ('is_active', models.BooleanField(default=False)),
        #         ('product_images', models.ImageField(blank=True, upload_to='photos/products/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>')),
        #         ('created_date', models.DateTimeField(auto_now_add=True)),
        #         ('modified_date', models.DateTimeField(auto_now=True)),
        #         ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
        #         ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Supply',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('supply_name', models.CharField(max_length=50)),
        #         ('supply_type', models.CharField(max_length=50)),
        #         ('stock', models.PositiveIntegerField()),
        #         ('min_stock', models.PositiveIntegerField()),
        #         ('active_stock', models.PositiveIntegerField()),
        #         ('cost', models.PositiveIntegerField()),
        #         ('min_price', models.PositiveIntegerField()),
        #         ('price', models.PositiveIntegerField()),
        #         ('size', models.CharField(choices=[('Ninguno', 'Ninguno'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXL', 'XXL'), ('11 Oz', '11 Oz'), ('15 Oz', '15 Oz'), ('12x24 cm', '12x24 cm'), ('30x60 cm', '30x60 cm')], max_length=30)),
        #         ('color', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Transparente', 'Transparente'), ('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Gris', 'Gris'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Morado', 'Morado'), ('Celeste', 'Celeste'), ('Amarillo', 'Amarillo')], max_length=30)),
        #         ('weight', models.FloatField()),
        #         ('is_active', models.BooleanField(default=False)),
        #         ('description', models.CharField(blank=True, max_length=255)),
        #         ('created_date', models.DateTimeField(auto_now_add=True)),
        #         ('modified_date', models.DateTimeField(auto_now=True)),
        #         ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
        #     ],
        #     options={
        #         'verbose_name': 'supply',
        #         'verbose_name_plural': 'supplies',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Tag',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('tag_info', models.CharField(max_length=50, unique=True)),
        #         ('tag_type', models.CharField(choices=[('Categoría', 'Categoría'), ('Contenedor', 'Contenedor'), ('Información', 'Información')], max_length=50)),
        #         ('tag_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tag')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='tags',
        #     field=models.ManyToManyField(to='store.tag'),
        # ),
    ]
