# Generated by Django 5.0.3 on 2024-03-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_rename_cat_image_category_category_image'),
        ('store', '0001_initial'),
    ]

    operations = [
        
    ]
