# Generated by Django 5.0.3 on 2024-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='size',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('11 Oz', '11 Oz'), ('15 Oz', '15 Oz'), ('12x24 cm', '12x24 cm'), ('30x60 cm', '30x60 cm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
