# Generated by Django 5.0.3 on 2024-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_supply_size_alter_supply_supply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
