# Generated by Django 5.0.3 on 2024-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_supply_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='slug',
            new_name='supply_slug',
        ),
    ]
