# Generated by Django 5.0.3 on 2024-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_supply_supply_name_alter_supply_supply_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='supply_slug',
        ),
    ]
