# Generated by Django 5.0.3 on 2024-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_supply_supply_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supply_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
