# Generated by Django 5.0.3 on 2024-03-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_tag_tag_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.tag'),
        ),
    ]
