# Generated by Django 5.0.3 on 2024-03-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_tag_tag_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_supply',
            name='category',
        ),
        migrations.AddField(
            model_name='product_supply',
            name='supply',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='store.supply'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_info',
            field=models.CharField(max_length=50),
        ),
    ]
