# Generated by Django 5.0.3 on 2024-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_supply_category_product_supply_supply_and_more'),
    ]

    operations = [
        
    ]
