# Generated by Django 5.0.3 on 2024-03-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_supply_delete_product_supply'),
    ]

    operations = [

    ]
