# Generated by Django 5.0.3 on 2024-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_ps_stock_remove_product_supply_and_more'),
    ]

    operations = [

    ]
