# Generated by Django 5.0.3 on 2024-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_supply_product_supply'),
    ]

    operations = [
        
    ]
