# Generated by Django 5.0.3 on 2024-03-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_delete_product_supply'),
    ]

    operations = [
        
    ]
