# Generated by Django 5.0.3 on 2024-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_product_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplies',
            field=models.ManyToManyField(to='store.supply'),
        ),

    ]
