# Generated by Django 5.0.3 on 2024-03-18 15:55

from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_product_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('product_images', models.ImageField(blank=True, upload_to='photos/products/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
