# Generated by Django 5.0.3 on 2024-03-18 16:16

from django.db import migrations

from django.db import migrations
from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_supplies_product_supp'),
    ]

    operations = [
        
    ]
