# Generated by Django 5.0.3 on 2024-03-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_supplies_product_supp_delete_product_supply'),
    ]

    operations = [

    ]
