# Generated by Django 5.0.3 on 2024-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_delete_product'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Product_Supplies',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_active', models.BooleanField(default=False)),
        #         ('created_date', models.DateTimeField(auto_now_add=True)),
        #         ('modified_date', models.DateTimeField(auto_now=True)),
        #     ],
        # ),
        
    ]

# "store_product_supply"
#  store_product_supplies