# Generated by Django 5.0.3 on 2024-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_supply_delete_product'),
    ]

    operations = [
  
    ]
