# Generated by Django 5.0.3 on 2024-03-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_supplies_product_supp_product_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_supply',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Supply',
        ),
    ]
