# Generated by Django 5.0.3 on 2024-03-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product'),
    ]

    operations = [
        
    ]
