# Generated by Django 5.0.3 on 2024-03-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_conection_product_supply_alter_product_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supply',
        ),
        migrations.CreateModel(
            name='Conection_Product_Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('product_images', models.ImageField(blank=True, upload_to='photos/products/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supply')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supply_resource',
            field=models.ManyToManyField(through='store.Conection_Product_Supply', to='store.supply'),
        ),
    ]
