# Generated by Django 5.0.3 on 2024-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_remove_product_supply_conection_product_supply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conection_product_supply',
            options={'verbose_name': 'Product supply', 'verbose_name_plural': 'Product supplies'},
        ),
        migrations.AlterField(
            model_name='conection_product_supply',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='conection_product_supply',
            name='ps_stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
