# Generated by Django 5.0.3 on 2024-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='color',
        ),
        migrations.AddField(
            model_name='supply',
            name='color',
            field=models.ManyToManyField(to='store.color'),
        ),
    ]
