# Generated by Django 5.0.3 on 2024-03-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_remove_supply_color_supply_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='color',
        ),
        migrations.AddField(
            model_name='supply',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.color'),
            preserve_default=False,
        ),
    ]
