# Generated by Django 5.0.3 on 2024-03-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_supply_color_supply_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conection_product_supply',
            name='product_images',
        ),
        migrations.CreateModel(
            name='Product_Color_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(blank=True, upload_to='photos/products/<django.db.models.fields.related.ForeignKey>/colors')),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Colors',
            field=models.ManyToManyField(through='store.Product_Color_Img', to='store.color'),
        ),
    ]
