# Generated by Django 5.0.3 on 2024-03-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_conection_product_supply_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Colors',
            new_name='colors',
        ),
    ]
